twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        supported_locales: '%app.supported_locales%'
        default_locale: '%app.locale%'
