version: '3.3'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app:delegated
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app:delegated
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/app:delegated
      - composer:/root/.composer/cache:delegated
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker
      dockerfile: mysql.docker
    volumes:
      - mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_USER: ria
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ria
      MYSQL_DATABASE: ria
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    ports:
      - 8020:80
    depends_on:
      - mysql

volumes:
  mysql:
  composer: