services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ria\Bundle\UserBundle\:
      resource: '../../'
      exclude:
          - '../src/DependencyInjection/'
          - '../src/Entity/'
          - '../src/Tests/'

  Ria\Bundle\UserBundle\Controller\:
      resource: "../../Controller"
      tags: ['controller.service_arguments']


  # Mapping commands to handlers
  create_user_handler:
    class: Ria\Bundle\UserBundle\Handler\User\CreateUserHandler
    tags:
      - { name: tactician.handler, typehints: true }