ria_admin:
  resource: "@RiaAdminBundle/Controller/"
  type: annotation

ria_posts:
  resource: "@RiaPostBundle/Controller/"
  type: annotation

ria_users:
    resource: "@RiaUserBundle/Controller/"
    type: annotation