services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Ria\Bundle\PostBundle\:
      resource: '../../'
      exclude:
          - '../src/DependencyInjection/'
          - '../src/Entity/'
          - '../src/Tests/'

  Ria\Bundle\PostBundle\Controller\:
      resource: "../../Controller"
      tags: ['controller.service_arguments']


  create.story.handler:
    class: Ria\Bundle\PostBundle\Handler\Story\CreateStoryHandler
    tags:
      - { name: tactician.handler, typehints: true }

#  twig_extension.admin:
#    class: Ria\Bundle\PostBundle\Twig\FlagIconExtension
#    tags: [ 'twig.extension' ]